version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wikidb
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2.5
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wikidb
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
